services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://host.docker.internal:11434/api/generate
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    dns:
      - 8.8.8.8   # Google Primary DNS
      - 8.8.4.4   # Google Secondary DNS
      - 1.1.1.1   #Cloudflare
      - 1.0.0.1
    command: python manage.py runserver 0.0.0.0:8000