import os
import requests
from core.services.preprocessor import preprocess_text
from core.services.indexer import build_chunked_index


def rank_chunks(query, inverted_index, chunk_mapping):
    """
    Ranks text chunks based on matching keyword frequencies.
    """
    tokens = preprocess_text(query)
    scores = {}

    for token in tokens:
        if token in inverted_index:
            for chunk_id, freq in inverted_index[token].items():
                scores[chunk_id] = scores.get(chunk_id, 0) + freq

    ranked_chunk_ids = sorted(scores, key=scores.get, reverse=True)
    
    # --- FIX: Extract the actual text string from the dictionary ---
    top_chunks = []
    for c_id in ranked_chunk_ids:
        if c_id in chunk_mapping:
            chunk_data = chunk_mapping[c_id]
            # Safely handle both dict formats and raw strings
            if isinstance(chunk_data, dict) and "text" in chunk_data:
                top_chunks.append(chunk_data["text"])
            elif isinstance(chunk_data, str):
                top_chunks.append(chunk_data)
                
    return top_chunks[:5]  # Return top 5 most relevant strings

def query_ollama(prompt, context):
    """
    Sends the user query and scoped document context to Ollama.
    """
    ollama_url = os.environ.get("OLLAMA_HOST", "http://host.docker.internal:11434/api/generate")
    
    rag_prompt = (
        f"--- DOCUMENT CONTEXT ---\n{context}\n\n"
        f"--- USER QUESTION ---\n{prompt}\n\n"
        "--- ANSWER ---"
    )

    try:
        response = requests.post(
            ollama_url,
            json={
                "model": "nimadea-tutor",  # Or 'llama3.2' if not using a custom Modelfile
                "prompt": rag_prompt,
                "stream": False
            },
            timeout=90
        )
        
        if response.status_code == 200:
            return response.json().get("response", "No response generated by AI.")
        return f"Ollama Error (HTTP {response.status_code}): {response.text}"
        
    except requests.exceptions.RequestException as e:
        return f"Could not reach Ollama at {ollama_url}. Ensure Ollama is running on your host machine."

def search_chunks_and_query_ollama(query, doc_dict):
    """
    Builds a temporary scoped index for the selected documents,
    retrieves the top matching text chunks, and sends them to Ollama.
    """
    if not doc_dict:
        return "No documents selected. Please check at least one document in your sidebar."

    # Index only the selected documents in the workspace
    inverted_index, chunk_mapping = build_chunked_index(doc_dict)
    top_chunks = rank_chunks(query, inverted_index, chunk_mapping)

    # Fallback to initial document text if no direct keyword match
    if not top_chunks:
        context = "\n---\n".join(list(doc_dict.values())[:2])[:2500]
    else:
        context = "\n---\n".join(top_chunks)

    return query_ollama(query, context)