import math
import os
import requests
from django.db.models import Q

from core.models import DocumentChunk
from core.services.preprocessor import preprocess_text
from core.services.indexer import build_chunked_index, build_embedding_from_text


def cosine_similarity(vec_a, vec_b):
    if not vec_a or not vec_b:
        return 0.0

    dot = sum(a * b for a, b in zip(vec_a, vec_b))
    norm_a = math.sqrt(sum(a * a for a in vec_a)) or 1.0
    norm_b = math.sqrt(sum(b * b for b in vec_b)) or 1.0
    return dot / (norm_a * norm_b)


def rank_chunks(query, inverted_index, chunk_mapping):
    """Legacy keyword-only ranking kept for compatibility."""
    tokens = preprocess_text(query)
    scores = {}

    for token in tokens:
        if token in inverted_index:
            for chunk_id, freq in inverted_index[token].items():
                scores[chunk_id] = scores.get(chunk_id, 0) + freq

    ranked_chunk_ids = sorted(scores, key=scores.get, reverse=True)

    top_chunks = []
    for c_id in ranked_chunk_ids:
        if c_id in chunk_mapping:
            chunk_data = chunk_mapping[c_id]
            if isinstance(chunk_data, dict) and "text" in chunk_data:
                top_chunks.append(chunk_data["text"])
            elif isinstance(chunk_data, str):
                top_chunks.append(chunk_data)

    return top_chunks[:5]


def hybrid_retrieve_chunks(query, workspace_id=None, document_ids=None, limit=5):
    """Hybrid retrieval combining lexical scoring and vector similarity."""
    query_tokens = set(preprocess_text(query))
    query_vector = build_embedding_from_text(query)

    filters = Q()
    if workspace_id is not None:
        filters &= Q(workspace_id=workspace_id)
    if document_ids:
        filters &= Q(document_id__in=document_ids)

    chunks = DocumentChunk.objects.filter(filters).order_by('document_id', 'chunk_index')

    scored = []
    for chunk in chunks:
        token_score = 0.0
        for token in query_tokens:
            if token in " ".join(preprocess_text(chunk.content)).lower():
                token_score += 1.0

        vector_score = cosine_similarity(query_vector, chunk.embedding or [0.0] * len(query_vector))
        combined = (token_score * 0.4) + (vector_score * 0.6)
        if combined <= 0 and not query_tokens:
            combined = 0.0

        scored.append({
            'chunk_id': chunk.id,
            'workspace_id': chunk.workspace_id,
            'document_id': chunk.document_id,
            'content': chunk.content,
            'section': chunk.section,
            'subsection': chunk.subsection,
            'page_number': chunk.page_number,
            'embedding': chunk.embedding,
            'score': combined,
            'keyword_score': token_score,
            'vector_score': vector_score,
        })

    scored.sort(key=lambda item: item['score'], reverse=True)
    return scored[:limit]


def build_context_from_candidates(candidates):
    """Build the final retrieval context and source metadata for the AI."""
    context_lines = []
    sources = []

    for item in candidates:
        content = (item.get('content') or '').strip()
        if not content:
            continue

        context_lines.append(content)
        sources.append({
            'chunk_id': item.get('chunk_id'),
            'document_id': item.get('document_id'),
            'workspace_id': item.get('workspace_id'),
            'section': item.get('section'),
            'subsection': item.get('subsection'),
            'page_number': item.get('page_number'),
            'score': item.get('score'),
        })

    return {
        'context': '\n---\n'.join(context_lines),
        'sources': sources,
    }

def query_ollama(prompt, context):
    ollama_url = os.environ.get("OLLAMA_API_URL", "http://host.docker.internal:11434/api/chat")

    payload = {
        "model": "qwen3.5:9b",
        "messages": [
            {
                "role": "user",
                "content": (
                    f"--- DOCUMENT CONTEXT ---\n{context}\n\n"
                    f"--- USER QUESTION ---\n{prompt}\n\n"
                    "--- ANSWER ---"
                ),
            }
        ],
        "think": False,  # top-level field; /no_think in the prompt text does NOT work for qwen3.5
        "stream": False,
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 800,  # hard cap so a runaway generation can't eat the whole timeout budget
        },
    }

    try:
        response = requests.post(ollama_url, json=payload, timeout=180)

        if response.status_code == 200:
            return response.json().get("message", {}).get("content", "No response generated by AI.")
        return f"Ollama Error (HTTP {response.status_code}): {response.text}"

    except requests.exceptions.Timeout:
        return "Ollama generation timed out. The model took longer than 180 seconds to respond."
    except requests.exceptions.RequestException as e:
        return f"Could not reach Ollama at {ollama_url}. Error: {str(e)}"
import time

def search_chunks_and_query_ollama(query, doc_dict):
    if not doc_dict:
        return "No documents selected. Please check at least one document in your sidebar."

    t0 = time.time()
    inverted_index, chunk_mapping = build_chunked_index(doc_dict)
    t1 = time.time()
    top_chunks = rank_chunks(query, inverted_index, chunk_mapping)
    t2 = time.time()

    if not top_chunks:
        context = "\n---\n".join(list(doc_dict.values())[:2])[:2500]
    else:
        context = "\n---\n".join(top_chunks)

    result = query_ollama(query, context)
    t3 = time.time()

    print(f"[timing] index build: {t1-t0:.1f}s | rank: {t2-t1:.1f}s | ollama: {t3-t2:.1f}s | total: {t3-t0:.1f}s")
    return result