import os
import requests
from core.services.preprocessor import preprocess_text
from core.services.indexer import build_chunked_index


def rank_chunks(query, inverted_index, chunk_mapping):
    """
    Ranks text chunks based on matching keyword frequencies.
    """
    tokens = preprocess_text(query)
    scores = {}

    for token in tokens:
        if token in inverted_index:
            for chunk_id, freq in inverted_index[token].items():
                scores[chunk_id] = scores.get(chunk_id, 0) + freq

    ranked_chunk_ids = sorted(scores, key=scores.get, reverse=True)
    
    # --- FIX: Extract the actual text string from the dictionary ---
    top_chunks = []
    for c_id in ranked_chunk_ids:
        if c_id in chunk_mapping:
            chunk_data = chunk_mapping[c_id]
            # Safely handle both dict formats and raw strings
            if isinstance(chunk_data, dict) and "text" in chunk_data:
                top_chunks.append(chunk_data["text"])
            elif isinstance(chunk_data, str):
                top_chunks.append(chunk_data)
                
    return top_chunks[:5]  # Return top 5 most relevant strings

def query_ollama(prompt, context):
    ollama_url = os.environ.get("OLLAMA_API_URL", "http://host.docker.internal:11434/api/chat")

    payload = {
        "model": "qwen3.5:9b",
        "messages": [
            {
                "role": "user",
                "content": (
                    f"--- DOCUMENT CONTEXT ---\n{context}\n\n"
                    f"--- USER QUESTION ---\n{prompt}\n\n"
                    "--- ANSWER ---"
                ),
            }
        ],
        "think": False,  # top-level field; /no_think in the prompt text does NOT work for qwen3.5
        "stream": False,
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 800,  # hard cap so a runaway generation can't eat the whole timeout budget
        },
    }

    try:
        response = requests.post(ollama_url, json=payload, timeout=180)

        if response.status_code == 200:
            return response.json().get("message", {}).get("content", "No response generated by AI.")
        return f"Ollama Error (HTTP {response.status_code}): {response.text}"

    except requests.exceptions.Timeout:
        return "Ollama generation timed out. The model took longer than 180 seconds to respond."
    except requests.exceptions.RequestException as e:
        return f"Could not reach Ollama at {ollama_url}. Error: {str(e)}"
import time

def search_chunks_and_query_ollama(query, doc_dict):
    if not doc_dict:
        return "No documents selected. Please check at least one document in your sidebar."

    t0 = time.time()
    inverted_index, chunk_mapping = build_chunked_index(doc_dict)
    t1 = time.time()
    top_chunks = rank_chunks(query, inverted_index, chunk_mapping)
    t2 = time.time()

    if not top_chunks:
        context = "\n---\n".join(list(doc_dict.values())[:2])[:2500]
    else:
        context = "\n---\n".join(top_chunks)

    result = query_ollama(query, context)
    t3 = time.time()

    print(f"[timing] index build: {t1-t0:.1f}s | rank: {t2-t1:.1f}s | ollama: {t3-t2:.1f}s | total: {t3-t0:.1f}s")
    return result