# Generated by Django 6.1 on 2026-08-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexstore',
            options={},
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
