# Generated by Django 6.1.1 on 2026-09-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_indexstore_options_document_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('subsection', models.CharField(blank=True, default='', max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.workspace')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'document', 'chunk_index'), name='unique_document_chunk_index')],
            },
        ),
    ]
