# Generated by Django 6.1.1 on 2026-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_document_file_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
